#!/bin/sh
# sshg-logtail -- poll from the ends of log files using `tail`
# This file is part of SSHGuard.

# Flag dialects
tailF="tail -F -n 0 $@"
tailf="tail -f -n 0 $@"

# On Linux, follow the file name not descriptor
tailL="tail --follow=name -n 0 $@"

fallback() {
    eval $tailF 2>/dev/null || exec $tailf
}

case `uname` in
    Darwin|FreeBSD|NetBSD)
        exec $tailF;;
    Linux)
        exec $tailL;;
    OpenBSD)
        exec $tailf;;
    *)
        fallback;;
esac
